package game;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DatabaseManager {
    private static final Logger LOGGER = Logger.getLogger(DatabaseManager.class.getName());
    // HSQLDB с сохранением в файл
    private static final String DB_URL = "jdbc:hsqldb:file:./battlehistory/battlehistory;shutdown=true";
    private static final String USER = "SA"; // Стандартный пользователь HSQLDB
    private static final String PASS = "";   // Пароль пустой
    private static Connection connection;

    static {
        try {
            // Регистрируем драйвер HSQLDB
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            initializeDatabase();
        } catch (ClassNotFoundException e) {
            LOGGER.log(Level.SEVERE, "Failed to load HSQLDB JDBC driver", e);
            throw new RuntimeException("Failed to load HSQLDB JDBC driver", e);
        }
    }

    private static void initializeDatabase() {
        try {
            LOGGER.info("Connecting to HSQLDB database: " + DB_URL);
            connection = DriverManager.getConnection(DB_URL, USER, PASS);
            connection.setAutoCommit(true);
            createTableIfNotExists();
            LOGGER.info("HSQLDB database initialized successfully");
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Failed to initialize HSQLDB database", e);
            throw new RuntimeException("Failed to initialize HSQLDB database", e);
        }
    }

    private static void createTableIfNotExists() throws SQLException {
        String checkTableSQL = "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'BATTLE_HISTORY'";
        String createTableSQL = """
            CREATE TABLE BATTLE_HISTORY (
                ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                PLAYER1 VARCHAR(50),
                PLAYER2 VARCHAR(50),
                WINNER VARCHAR(50),
                GAME_MODE VARCHAR(20),
                BATTLE_DATE TIMESTAMP
            )
        """;

        try (Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(checkTableSQL)) {
            if (!rs.next()) {
                try (Statement createStmt = connection.createStatement()) {
                    createStmt.executeUpdate(createTableSQL);
                    LOGGER.info("Table BATTLE_HISTORY created successfully");
                }
            } else {
                LOGGER.info("Table BATTLE_HISTORY already exists");
            }
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error checking/creating table BATTLE_HISTORY", e);
            throw e;
        }
    }

    public static void saveGameResult(String player1, String player2, String winner, String gameMode, Timestamp timestamp) {
        String sql = "INSERT INTO BATTLE_HISTORY (PLAYER1, PLAYER2, WINNER, GAME_MODE, BATTLE_DATE) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setString(1, player1);
            stmt.setString(2, player2);
            stmt.setString(3, winner);
            stmt.setString(4, gameMode);
            stmt.setTimestamp(5, timestamp);
            stmt.executeUpdate();
            LOGGER.fine("Game result saved successfully");
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error saving game result", e);
        }
    }

    public static List<BattleRecord> getBattleHistory() {
        List<BattleRecord> history = new ArrayList<>();
        String sql = "SELECT * FROM BATTLE_HISTORY ORDER BY BATTLE_DATE DESC";
        try (Statement stmt = connection.createStatement();
             ResultSet rs = stmt.executeQuery(sql)) {
            while (rs.next()) {
                BattleRecord record = new BattleRecord(
                        rs.getString("PLAYER1"),
                        rs.getString("PLAYER2"),
                        rs.getString("WINNER"),
                        rs.getString("GAME_MODE"),
                        rs.getTimestamp("BATTLE_DATE")
                );
                history.add(record);
            }
            LOGGER.fine("Battle history retrieved successfully");
        } catch (SQLException e) {
            LOGGER.log(Level.SEVERE, "Error retrieving battle history", e);
        }
        return history;
    }

    public static void closeConnection() {
        try {
            if (connection != null && !connection.isClosed()) {
                // Выполняем SHUTDOWN для корректного сохранения данных
                try (Statement stmt = connection.createStatement()) {
                    stmt.execute("SHUTDOWN");
                }
                connection.close();
                LOGGER.info("Database connection closed and data saved");
            }
        } catch (SQLException e) {
            LOGGER.log(Level.WARNING, "Error closing database connection", e);
        }
    }
}